- name: print Linux
  hosts: all
  tasks:
    - name: print to Linux
      ansible.builtin.debug:
        msg: Hello, Linux
      when: os_name == "linux"

    - name: print to Linux
      ansible.builtin.debug:
        msg: Hello, Linux
      when: os_name == "uinux"