- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copying Expense Config
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - App Prerequites
  ansible.builtin.import_roles:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: enable and restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

